<header id="site-header" class="site-header">
  <div class="site-container">

    <div class="header-back-img">
      <div class="logo-description-wrapper">

        <div class="logo">
          <a href="15-1956-Homepage_4.php"><img src="theme/images/logo.png" alt="logo"/>
          </a>
        </div>

        <h2>Total Wheel Management System </h2>

        <div class="description">
          Ensure that optimal PSI is maintained at all times, dynamically,
          with the Drov Total Wheel Management System.
        </div>

      </div>
    </div>
  </div>
</header>