<header id="site-header" class="site-header">
  <div class="site-container">

    <div class="header-back-img">
      <div class="logo-description-wrapper">

        <div class="logo">
          <a href="15-1956-Homepage_4.php"><img src="theme/images/logo.png" alt="logo"/>
          </a>
        </div>

        <h2>Total Wheel Management System </h2>

        <div class="description">
          Ensure that optimal PSI is maintained at all times, dynamically,
          with the Drov Total Wheel Management System.
        </div>

      </div>

    </div>

    <div class="col-wrapper width-padding">
      <div class="cols">
        <div class="col col-1">
          <h4>DR<span class="o">O</span>V TIRE
            INFLATION</h4>
        </div>
        <div class="col col-2">
          <h4>DR<span class="o">O</span>V
            INTELLIGENT
            SYSTEM</h4>
        </div>
        <div class="col col-3">
          <h4>
            <span>DR<span class="o">O</span>V
            ANALYTICS</span>
          </h4>
          <div class="text">
            Logistics Productivity & Analysis
          </div>

          <ul>
            <li>Tire RIO</li>
            <li>Compliance</li>
            <li>Fuel Effeciency</li>
            <li>Fleet Utilization & KPI’s</li>
            <li>Vendor Comparative Analysis</li>
            <li>Preventive Maintenance Effectiveness</li>
          </ul>

        </div>
      </div>

    </div>
  </div>
</header>